before_script:
- 'echo TRAVIS_BRANCH: $TRAVIS_BRANCH'
- 'echo TRAVIS_PULL_REQUEST: $TRAVIS_PULL_REQUEST'
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- pip3 install -r requirements.txt
- python3 ./generate-matrix.py >/dev/null && git diff --exit-code
os: linux
dist: bionic
env:
  jobs:
  - TOMCAT_VERSION=8.5 TOMCAT_JAVA_VERSION=jdk8-openjdk TOMCAT_BASE_IMAGE= LUCEE_MINOR=5.2 LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=8.5 TOMCAT_JAVA_VERSION=jdk11-openjdk TOMCAT_BASE_IMAGE= LUCEE_MINOR=5.2 LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=9.0 TOMCAT_JAVA_VERSION=jdk8-openjdk TOMCAT_BASE_IMAGE= LUCEE_MINOR=5.2,5.3 LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
  - TOMCAT_VERSION=9.0 TOMCAT_JAVA_VERSION=jdk11-openjdk TOMCAT_BASE_IMAGE= LUCEE_MINOR=5.2,5.3 LUCEE_SERVER=,-nginx LUCEE_VARIANTS=,-light
language: python
python: 3.6
script:
- echo $LUCEE_VERSION
- python3 -u build-images.py
services:
- docker
