lucee:
  image: lucee/lucee:5.3-nginx
  environment:
    - VIRTUAL_HOST=lucee-dockerfiles.*
  volumes:
    - "/workbench/lucee-dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    - "/workbench/lucee-dockerfiles/www:/var/www"
  ports: 
    - "8853:8888"
    - "8053:80"
